2014-12-21 12:37:17+00:00

diff --git a/net-irc/eggdrop/files/eggdrop-installer b/net-irc/eggdrop/files/eggdrop-installer
--- a/net-irc/eggdrop/files/eggdrop-installer
+++ b/net-irc/eggdrop/files/eggdrop-installer
@@ -1,10 +1,10 @@
 #!/bin/bash
-# Copyright 1999-2005 Gentoo Foundation
+# Copyright 1999-2014 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/net-irc/eggdrop/files/eggdrop-installer,v 1.10 2007/03/14 17:52:24 drac Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-irc/eggdrop/files/eggdrop-installer,v 1.11 2014/12/21 12:08:00 mgorny Exp $
 
-source /etc/init.d/functions.sh || {
-	echo "${0}: Could not source /etc/init.d/functions.sh!"
+source /lib/gentoo/functions.sh || {
+	echo "${0}: Could not source /lib/gentoo/functions.sh!"
 	exit 1
 }
 
