2015-06-18 09:07:09+00:00

diff --git a/net-misc/teamviewer/files/teamviewerd.init b/net-misc/teamviewer/files/teamviewerd.init
--- a/net-misc/teamviewer/files/teamviewerd.init
+++ b/net-misc/teamviewer/files/teamviewerd.init
@@ -1,26 +1,31 @@
-#!/sbin/runscript
-# Copyright 1999-2013 Gentoo Foundation
+#!/sbin/openrc-run
+# Copyright 1999-2015 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/net-misc/teamviewer/files/teamviewerd.init,v 1.2 2013/04/18 13:08:45 hasufell Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-misc/teamviewer/files/teamviewerd.init,v 1.3 2015/06/18 08:35:17 np-hardass Exp $
 
+command=/opt/teamviewer@TVV@/tv_bin/teamviewerd
+command_args=-d
 description="daemon for TeamViewer"
+pidfile=/var/run/teamviewerd.pid
 
-PIDFILE="/var/run/teamviewerd.pid"
+extra_stopped_commands="passwd"
 
-start() {
-	ebegin "Starting Teamviewer Daemon"
+passwd() {
+	if [ -z "${PASSWD}" ]; then
+		eerror "No password specified."
+		exit 1
+	fi
 
-	start-stop-daemon \
-		--start \
-		--pidfile "${PIDFILE}" \
-		--background \
-		--exec /opt/teamviewer@TVV@/teamviewerd -- -d
-}
-
-stop() {
-	ebegin "Stopping Teamviewer Daemon"
-
-	start-stop-daemon \
-		--stop \
-		--pidfile "${PIDFILE}"
+	ebegin "Attempting to change password."
+	/opt/teamviewer@TVV@/tv_bin/teamviewerd --passwd "${PASSWD}"
+	retr=$?
+	case $retr in
+		0)	einfo "Password successfully set." ;;
+		11|12)	eerror "Password must be between 8 and 12 characters.";;
+		13)	eerror "Invalid characters detected.";;
+		14)	eerror "Password invalid. Validation failed.";;
+		*)	eerror "Unknown error code";;
+	esac
+	eend $retr
+	exit $retr
 }
