2014-12-15 00:07:02+00:00

diff --git a/net-analyzer/icinga2/files/icinga2.initd b/net-analyzer/icinga2/files/icinga2.initd
--- a/net-analyzer/icinga2/files/icinga2.initd
+++ b/net-analyzer/icinga2/files/icinga2.initd
@@ -20,8 +20,16 @@ checkconfig() {
        eend 1
     fi
 
-    ICINGA2_USER=`$DAEMON variable get --current RunAsUser`
-    ICINGA2_GROUP=`$DAEMON variable get --current RunAsGroup`
+    ICINGA2_USER=$($DAEMON variable get --current RunAsUser)
+    if [ $? != 0 ]; then
+        eerror "Could not fetch RunAsUser variable: '$ICINGA2_USER'."
+        return 1
+    fi
+    ICINGA2_GROUP=$($DAEMON variable get --current RunAsGroup)
+    if [ $? != 0 ]; then
+        eerror "Could not fetch RunAsGroup variable: '$ICINGA2_GROUP'."
+        return 1
+    fi
 
     checkpath -d -m 0750 -o $ICINGA2_USER:$ICINGA2_GROUP $ICINGA2_RUN_DIR
     checkpath -d -m 0750 -o $ICINGA2_USER:$ICINGA2_COMMAND_GROUP $ICINGA2_STATE_DIR
