2015-03-11 05:06:52+00:00

diff --git a/net-analyzer/icinga2/files/icinga2.initd b/net-analyzer/icinga2/files/icinga2.initd
--- a/net-analyzer/icinga2/files/icinga2.initd
+++ b/net-analyzer/icinga2/files/icinga2.initd
@@ -2,6 +2,8 @@
 # Copyright 1999-2015 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+extra_started_commands="reload"
+
 DAEMON="/usr/sbin/icinga2"
 ICINGA2_CONFIG_FILE="/etc/icinga2/icinga2.conf"
 ICINGA2_RUN_DIR="/run/icinga2"
@@ -32,11 +34,11 @@ checkconfig() {
     fi
 
     checkpath -d -m 0750 -o $ICINGA2_USER:$ICINGA2_GROUP $ICINGA2_RUN_DIR
-    checkpath -d -m 0750 -o $ICINGA2_USER:$ICINGA2_COMMAND_GROUP $ICINGA2_STATE_DIR
-    checkpath -d -m 2750 -o $ICINGA2_USER:$ICINGA2_COMMAND_GROUP $ICINGA2_CMD_DIR
+    checkpath -d -m 0750 -o $ICINGA2_USER:$ICINGA2_GROUP $ICINGA2_STATE_DIR
+    checkpath -d -m 2750 -o $ICINGA2_USER:$ICINGA2_GROUP $ICINGA2_CMD_DIR
 
     if ! $DAEMON daemon -c $ICINGA2_CONFIG_FILE -C > $ICINGA2_STARTUP_LOG 2>&1; then
-        eerror "Icinga 2 detected configuration errors. Check '$ICINGA2_STARTUP_LOG' for details."
+        eerror "Icinga2 detected configuration errors. Check '$ICINGA2_STARTUP_LOG' for details."
         return 1
     fi
 }
@@ -63,4 +65,15 @@ stop() {
         --retry "SIGTERM/15 SIGKILL/30" \
         --progress
     eend $?
+}
+
+reload() {
+    ebegin "Checking icinga2 configuration"
+    "$DAEMON" daemon --validate >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        eerror "Icinga2 detected configuration errors, run '$DAEMON daemon --validate' for details"
+        return 1
+    fi
+    ebegin "Reloading icinga2"
+    start-stop-daemon --signal HUP "$ICINGA2_PID_FILE"
 }
